### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by robi-wan**
- Fixes error during creation of temporary copy of sms db:
  On Windows, open is required with option 'b'
- Catches any connection exceptions and raises them.
  I executed the script and got an error message indicating that multiple processes
  are accessing the temporary sms db copy. After diving deep in I discovered that accessing
  sms db generated an exception so that conn.close() in line 633 was not executed but
  the finally was executed where COPY_DB was also accessed: os.remove(COPY_DB).
  I added try:except to get this message:
  'sqlite3.DatabaseError: database disk image is malformed'
  But accessing the sms db with the native sqlite client worked.
  So the usual suspect was my python installation (2.7.2 32-bit on Windows 7 64-bit):
  The typical python installation comes with sqlite v3.6.21;
  I updated the sqlite3.dll in my python installation
  (see http://groups.google.com/group/python-sqlite/browse_thread/thread/9fb6694c803431eb)
  to current sqlite v3.7.10 - and the script worked expected.
  Maybe a lower sqlite version is sufficient - but I did not manage to find
  out which sqlite version iOS 5.0.1 uses (which runs on my iPhone 4).

Maybe the update of the sqlite version used by python should be mentioned in readme?

### CODE REVIEW

**Comment by toffer** [comment]
robi-wan,

Thanks for submitting this.  It's good to know there are some Windows users using the script!
- Adding the 'b' option to open() is a good catch.
- I'm confused about "multiple processes accessing the sms db copy".  Could you send me that error message?  In my original, it's true that conn.close() doesn't get called if there's an error connecting to the db, but os.remove() always gets called in the finally clause, so I didn't think it would matter.  If connection to the DB fails, DB is deleted and script finishes. Where do the multiple processes connecting come from?

As for your proposed solution, I'm concerned if there is an error in conn = sqlite3.connect(COPY_DB), then conn will be undefined, and you therefore can't call conn.close() in the finally clause.
- Thanks for the info about the problems you experienced with the different sqlite versions. I don't know much about that, so I guess I need to research that more.

**Comment by robi-wan** [comment]
Here are some more information about the failing os.remove()

I reverted all changes in script and the sqlite3 dll used from my python
installation.

call:
python sms-backup.py --input test\original\sms.db

Result:
Traceback (most recent call last):
  File "sms-backup.py", line 642, in <module>
    main()
  File "sms-backup.py", line 637, in main
    os.remove(COPY_DB)
WindowsError: [Error 32] Der Prozess kann nicht auf die Datei zugreifen, da
sie von einem anderen Prozess verwendet wird: 'c:\users\user_name\appdata\local\temp\tmperpse
n'

This means: "The process can not access the file because it is being used by
another process". The sms db file cannot be deleted while a sqlite3 connection
is opened to this file.
(This is windows...)

Line 610 with "cur.execute(query, params))" raised an exception (see below) -
all following code (including line 633 with "conn.close()") is skipped)
The finally block in line 635 is executed: there it tries in line 637 to delete the
temporary copy of the sms db - but this file is still accessed because in line
606 it created a connection to this file (and this connection is not closed as
the line 633 "conn.close()" was not executed). 

Next step:
I added a try:except block around lines 606-612:
  try:
    [..]
  except:
    conn.close()
    raise

This catches all exceptions, closes the connection to the sms db and then
re-raises the exception. (In my pull request I moved "conn.close()" to the
finally block to make sure that the connection is always closed.)

Call:
python sms-backup.py --input test\original\sms.db

Result:
Traceback (most recent call last):
  File "sms-backup.py", line 646, in <module>
    main()
  File "sms-backup.py", line 611, in main
    cur.execute(query, params)
sqlite3.DatabaseError: database disk image is malformed

The finally block code is successfully executed and the original exception is
shown. (This malformed database error is caused by the old version of sqlite3
dll in the python installation.)

**Comment by toffer** [comment]
robi-wan,

Thanks for your patience on this.

I changed around the try/except/finally logic in main(), so it should catch and handle the errors you were seeing.  Please give it a try and let me know if you are still experiencing problems.

Thanks,
Tom

**Comment by robi-wan** [comment]
Hi,

sorry for the delay in response.
I tried the current version and it worked as expected.

Thanks,

robi-wan

**Comment by toffer** [comment]
Glad to hear it!

**Pull request closed without merging**
