### PR TITLE
Pull Request to update to iOS 6 database

### PR DESCRIPTION
**Pull request by amlweems**
In iOS 6, Apple updated their database storage system. Their new database simplifies things greatly and removes the need to differentiate between SMS and iMessage. Apple's soon to be released Messages app will include the new database system as well. Apple will auto-update old databases to the new version. This update is meant to be used only with the new database system.

### CODE REVIEW

**Comment by toffer** [comment]
Wow. I haven't looked at iOS 6 at all, so thanks for the heads up and for updating the script. Simplifying the schema is a big change, but a most welcome one.

Ideally, I'd like the script to support both the older schema as well as the new one (for those who don't upgrade their iOS right away), so I'm not quite ready to delete code as aggressively as you did here.

**Comment by amlweems** [comment]
I know what you mean, I was just trying to get a working copy for iOS 6. The actual merging of the two will just involve lots of version checking and legacy code. Hopefully, you'll be able to use my version to make updating a bit easier.

**Comment by John07** [comment]
I've tried running this updated version on an iOS 6 database, but it only returns the help text no matter what parameters I choose. Any ideas?

**Comment by toffer** [comment]
iOS6 support added in 63ebe48ae0.

**Pull request closed without merging**
